### ISSUE TITLE
Does this installation include a local Search Server?

### ISSUE THREAD

**Issue by patpowerman** [technexo/musicbrainz#1]
Thank you very much for your scripts!
I'm not sure: Does this installation includes the local Search Server as explained here:
https://wiki.musicbrainz.org/Development/Search_server_setup
and the source code from:
https://bitbucket.org/metabrainz/search-server

**Comment by abhishio** [comment]
Yes, It does. It also includes MusicBrains Web Services.
Sorry for late reply.
